import Head from "next/head";
import Router from "next/router";
import { useEffect } from "react";

const Redirect = () => {
  useEffect(() => {
    Router.push("/earth");
  }, []);

  return (
    <div>
      <Head>
        <title>Planets Fact Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Redirect;
