import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/Button';
import Nav from '../components/Nav';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Planets Fact Site</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Image
        src='/assets/bg-stars.svg'
        layout='fill'
        objectFit='cover'
        objectPosition='center'
        alt='background stars'
      />
      <Nav />
      <main>Main</main>
    </>
  );
};

export default Home;

// type TechnologyCardProps = {
//   name: string;
//   description: string;
//   documentation: string;
// };

// const TechnologyCard = ({
//   name,
//   description,
//   documentation,
// }: TechnologyCardProps) => {
//   return (
//     <section className='flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105'>
//       <h2 className='text-lg text-gray-700'>{name}</h2>
//       <p className='text-sm text-gray-600'>{description}</p>
//       <a
//         className='mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2'
//         href={documentation}
//         target='_blank'
//         rel='noreferrer'
//       >
//         Documentation
//       </a>
//     </section>
//   );
// };
